project:
  type: website
  resources: 
    - data/
  render:
    - "*.qmd"
    - "!dataproc/"

website:
  title: "AKFIN - Sea Ice"
  
  navbar:
    background: primary
    foreground: light
    left:
      - href: daily-ts.qmd
        text: "Daily Time Series"
      - href: annual-ts.qmd
        text: "Annualized Time Series"
      - href: extent.qmd
        text: "About Sea Ice Extent"

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body: custom.js
    toc: true
    toc-depth: 2
    toc-location: left
    grid:
      sidebar-width: 250px
      body-width: 1200px
      margin-width: 100px
      gutter-width: 1.5rem

exclude:
  - "scripts/"
  - "dataproc/"

editor: visual