project:
  type: website
  resources: 
    - data/
  render:
    - "*.qmd"
    - "!dataproc/"

website:
  title: "AKFIN - Sea Ice"

  navbar:
    background: primary
    foreground: light
    left:
      - text: "Sea Ice Extent"
        menu:
          - href: extent.qmd
            text: "about Sea Ice Extent" 
          - href: sic-ts-daily.qmd
            text: "Daily Time Series"
          - href: sic-ts-annual.qmd
            text: "Annualized Time Series"
      - text: "Sea Ice Thickness"
        menu:
          - href: sit.qmd
            text: "about Sea Ice Thickness"
          - href: sit-ts-daily.qmd
            text: "Daily Time Series"
          - href: sit-ts-annual.qmd
            text: "Annualized Time Series"



format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body: custom.js
    toc: true
    toc-depth: 2
    toc-location: left
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 100px
      gutter-width: 1.5rem

exclude:
  - "scripts/"
  - "dataproc/"

editor: visual